### ISSUE TITLE
Report .net Core

### ISSUE THREAD

**Issue by nandkumariitr** [stimulsoft/Samples-NET.Core-JS-CSharp#5]
Hi,

I am trying to view or design the report by passing the custom data, but its not rendering? Any Idea? 

public IActionResult GetReport()
        {
            return StiNetCoreViewer.GetReportResult(this, string.Empty);
        }

        public IActionResult GetReportData()
        {           
            mqd mqd = new mqd("test", "QueryName", CommandBehavior.SchemaOnly);

            var dataTable = mqd.GetQueryResults();
            Stimulsoft.Report.NetCore.StiReportResult result = new StiReportResult();
            //result.Report = 
            StiDataResult stiDataResult = new StiDataResult();

            StiReportResult stiReportResult = new StiReportResult();
            
            var columns = dataTable.Columns.Select(x => x.Id).ToArray();
            var types = dataTable.Columns.Select(x=>x.TypeName.Split(".")[1].ToUpper() == "STRING" ? "string" : "number").ToArray();
            stiDataResult.Columns = columns;
            stiDataResult.Types = types;
            // var rows = dataTable.Rows.Select(x=>x.ColumnValues).ToArray();
            var count = dataTable.TotalRows;
            var rows = new string[count][];
            for(var item = 0; item < count; item++)
            {
                rows.SetValue(dataTable.Rows[item].ColumnValues.Select(x=>System.Convert.ToString(x)).ToArray(), item);
            }
            
            stiDataResult.Rows = rows;

            stiDataResult.ConnectionName = "TestConnection";
            stiDataResult.ConnectionType = StiConnectionType.JSON;
            
            return StiNetCoreViewer.GetReportDataResult(this, stiDataResult); 
        }

        public IActionResult ViewerEvent()
        {
            return StiNetCoreViewer.ViewerEventResult(this);
        }

**Comment by VladimirBLR** [comment]
Hello,

At this moment you can only transfer the data for the report SQL connection in this way. The provided data must have exactly the same structure as in the report dictionary. Also, you can use JSON and XML data as data result. 

We have plans to release a full-featured report engine for NET Core within two or three months.

Thank you.

**Comment by nandkumariitr** [comment]
Can i create a custom datasource(Any Example would be appreciated) in .net core and then pass the values into it in the same way? Is it mandatory to use SimpleList.mrt or a report template?

**Comment by VladimirBLR** [comment]
Currently you can use SQL connection in the report, and pass the StiDataResult object in the GetReportData() event. Also you can use XML or JSON connections in the report, and in the GetReportData() event pass the prepared XML or JSON data file.

Thank you.

**Comment by nandkumariitr** [comment]
Our use case is not to connect to the DB directly, Is it possible to create custom data source in .net Core and register it?

**Comment by VladimirBLR** [comment]
Currently there is no such possibility, only data sources available in the designer.

Thank you.

**Comment by nandkumariitr** [comment]
Ok, Thanks For the prompt reply..
Is there any BlankReport.mrt which i can use to design the report by passing my JSON data?

**Comment by VladimirBLR** [comment]
You can create in in the NET Core HTML5 designer:
1. Create a blank report.
2. Add new JSON data source, when the data is requested, the GetReportData() event will be called in which you can send your JSON.

![image](https://user-images.githubusercontent.com/19527128/30901467-9cc201de-a370-11e7-8c65-3975d0ac83ea.png)

Thank you.
