### ISSUE TITLE
Net Core Data XML not render

### ISSUE THREAD

**Issue by pedromalito** [stimulsoft/Samples-NET.Core-JS-CSharp#6]
I have a problem with render a xml file . Im import the schema in stimulsoft, but when load the data not show nothing
I trying about diferent methods as DataSet 

   string pathData ="\\data\\data.xml";      
                string data = _hostEnvironment.WebRootPath + "\\" + pathData;
                DataSet objDatos = new DataSet();

                objDatos.ReadXml(data);

            
                return StiNetCoreViewer.GetReportDataResult(this,objDatos);

And this method from xml 
  string pathData ="\\data\\data.xml";      
                string data = _hostEnvironment.WebRootPath + "\\" + pathData;
//also System.IO.File.ReadAllText(_hostEnvironment.WebRootPath + "\\" + pathData); 

      return StiNetCoreViewer.GetReportDataResult(this,objDatos,data );

My XML File and xsd file

[data.zip](https://github.com/stimulsoft/Samples-NET.Core-CSharp/files/1404560/data.zip)

**Comment by VladimirBLR** [comment]
Hello,

Currently the DataSet object is not supported, version NetCoreApp 2.0 in the development process and will soon be available. As a parameter, please use the path to the XML file or XML file as a string.

`return StiNetCoreViewer.GetReportDataResult(this, _hostEnvironment.WebRootPath + "\" + pathData);`

Thank you.

**Comment by pedromalito** [comment]
I use the method that you mentioned . but not load the info about xml.  I created mrt and load data as xml and nothing .

**Comment by VladimirBLR** [comment]
We have analyzed your data in more detail. At the moment, only full XML data is supported, without additional loading by URL. The DataSet functionality will be available soon, such data will most likely be supported.

Thank you.

**Comment by pedromalito** [comment]
I hope this feature well be available in this year :D

**Comment by VladimirBLR** [comment]
The pure .NET Core engine with Web components is scheduled for release 2018.1, which will be released in December this year. Thank you for your interest in the product.

**Comment by VladimirBLR** [comment]
Hello,

By the link the beta version of our tool compatible with .NET Core 2.0 is available https://www.nuget.org/packages/Stimulsoft.Reports.Mvc

Examples of using can be found in the following repository on GitHub at https://github.com/stimulsoft/Samples-NET.Core-MVC-CSharp

Thank you.

**Comment by pedromalito** [comment]
Thanks! Im testing this version but only one problem with images and sum for example this not run

{SumIfRunning(DataBand4,Traslado.Importe,Traslado.Impuesto = "003" and Traslado.Base>0)}

sumifrunning is valid?

**Comment by VladimirBLR** [comment]
Hello,

There are some problems with the SumRunning function. Please send us your report and, if possible, the data for testing to support@stimulsoft.com. We will try to resolve this issue.

Please indicate what are problems with images?

Also, we updated the version to 2017.2.4-rc2, some problems with export and report generation were solved. The new version is on NuGet, and the examples on GitHub are also updated.

Thank you.

**Comment by pedromalito** [comment]
[Adenda-CFDI-ACO560518KW7-ARR-2.zip](https://github.com/stimulsoft/Samples-NET.Core-JS-CSharp/files/1519712/Adenda-CFDI-ACO560518KW7-ARR-2.zip)
Ok I send the report and the data here!

**Comment by AlexKulikow** [comment]
Hello,

You should use the following expression:
{SumIf(DataBand4,Traslado.Importe,Traslado.Impuesto == "002" && Decimal.Parse(Traslado.Base)>0)}

Thank you.
