### ISSUE TITLE
Error in stimulsoft.

### ISSUE THREAD

**Issue by irajchardoli** [stimulsoft/Samples-NET.Core-JS-CSharp#7]
Hi , 
I use Stimulsoft.Reports.Mvc both of versions , but i have error:

`  at Stimulsoft.System.Drawing.Graphics.Finalize() in d:\Stimulsoft\Stimulsoft.Reports\.NetCore\Stimulsoft.System\Drawing\Graphics.cs:line 88

`
![stimulerror](https://user-images.githubusercontent.com/5341505/33167941-6bb0328a-d054-11e7-9382-602bc2a4c275.png)

**Comment by VladimirBLR** [comment]
Hello,

Please try to use the new version of the Stimulsoft Reports.Web for .NET Core:
https://www.nuget.org/packages/Stimulsoft.Reports.Web.NetCore/

And the sample projects for .NET Core 2.0:
https://github.com/stimulsoft/Samples-ASP.NET-MVC-CSharp
