### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by azharuddinsayed** [stimulsoft/Samples-NET.Core-JS-CSharp#9]
After clone the project is not even building showing a lot of error.

**Comment by VladimirBLR** [comment]
Hello. We could not reproduce the error, Visual Studio 2017, installed the latest updates:

========== Rebuild All: 15 succeeded, 0 failed, 0 skipped ==========

After running the solution, please try to run "Restore Nuget Packages", then "Rebuild Solution".

Thank you.

**Comment by azharuddinsayed** [comment]
Actually the issue is we have to update all the packages as the packages are old .

**Comment by VladimirBLR** [comment]
This version is the latest for NetCore-JS, and is no longer supported. Please see another repository with examples for the new version with native NetCore engine:

https://github.com/stimulsoft/Samples-ASP.NET-MVC-CSharp
